config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :messages do
    resources :comments
  end
  # generate a bunch of URLS for our messages controller associated with actions in the controller
  root 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  resourcify
  belongs_to :user
  has_many :comments
end

app/models/role.rb
class Role < ApplicationRecord
  # this is a 2 way relationship. This is saying that a user has many roles and it belongs to many users.
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  # this is a callback to tell the db when to create the default role.
  after_create :assign_default_role

  rolify
  has_many :messages
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

# this is now assigning every User database entry the role of a Moderator AS WELL AS the role of member because member is the default role.
  # user = User.last
  # user.add_role :moderator, Message


  # This is to add a default role.
   def assign_default_role
     self.add_role(:member) if self.roles.blank?
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index, :show]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_message
  before_action :find_comment, only: [:edit, :update, :destroy]
  # this gives us the ability to create a comment in respect to the current user.
  def create
    # finding the message
    # @message = Message.find(params[:message_id])
    # creating the comment in relation to that message.
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id
    # tis will save the comment and test if it has been saved, redirecting it to the current message so it'll show the comment underneath the message.
    if @comment.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end

  def edit
    # to edit something we have to find it first because this is a separate action that is happening in relation to all the other actions
    # this finds the current message by using the params

  end

  def update

    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    # head back to the message path in respect to where the message was in. This is where the functionality ends 1:18 hr:min
    redirect_to message_path(@message)
  end

  private

    def comment_params
      # name of the model and the attribute
      params.require(:comment).permit(:content)

    end

    def find_message
      @message = Message.find(params[:message_id])
    end

    def find_comment
      @comment = @message.comments.find(params[:id])
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :find_message, only: [:show, :edit, :update, :destroy]


  def index
    @messages = Message.all.order("created_at DESC")
    #  this will put the most recent messages at the top
  end

  def show

  end

  def new
    # current_user is a devise helper and this will create the new message of the current user. kind of like Message.new but it is associated with the current user.
    @message = current_user.messages.build
    # this is an instance variable and able to be used in the html.erb text
    
 #    Message Load (0.1ms)  SELECT  "messages".* FROM "messages" ORDER BY "messages"."id" DESC LIMIT ?  [["LIMIT", 1]]
 # => #<Message id: 3, title: "What is this going on?", description: "This is going to be a thing that we are creating", created_at: "2017-04-02 07:57:29", updated_at: "2017-04-02 07:57:29", user_id: 1>
  end

  def create
    @message = current_user.messages.build(message_params)

    if @message.save
      redirect_to root_path
    else
      render 'new'
    end

  end

  def edit

  end

  def update
    # this will not have a view because it'll be redirecting
    if @message.update(message_params)
      redirect_to  message_path
    else
      render 'edit'
    end
  end

  def destroy
    @message.destroy
    redirect_to root_path

  end

  private

    def message_params
      params.require(:message).permit(:title,:description)
    end

    def find_message
      @message = Message.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p class="comment-content"><%= comment.content %></p>
  <p class="comment-posted-by">Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at)%> ago</p>

  <!--
  /messages/3/comments/1
  comment.message corresponds to the message that the comments are for on the show page and will find the message that we are replying to.
  comment.message gets /messages/3
  comment represents the individual comment that is in relation to the message.
  comment gets /comments/1
  -->
  <div class="links">
    <% if user_signed_in? %>
      <% if comment.user_id == current_user.id %>
        <%= link_to "Edit", edit_message_comment_path(comment.message, comment) %>
        <%= link_to "Delete", message_comment_path(comment.message, comment), method: :delete, data: { confirm: "Are you sure?"} %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<!--  this is rendering on the show page of the message and it's going to build comments from that message
the first @message is getting the message that we are on
the second @message is building comments in relation to that message-->
<%= simple_form_for([@message,@message.comments.build]) do |f| %>
  <%= f.input :content, label: "Comment" %>
  <%= f.button :submit, :class => "btn-custom" %>
<% end %>

app/views/comments/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Edit Comment</h1>
  <%= simple_form_for([@message, @comment]) do |f| %>
    <%= f.input :content, label: "Comment" %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Message Board", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "Log In", new_user_session_path %></li>
            <% end %>
        </ul>
        <% if user_signed_in? %>
          <p><%= link_to "New Message", new_message_path, class: "navbar-right navbar-text navbar-link" %></p>
        <% end %>
      </div>
    </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label: "Message Title" %>
  <!-- if no label is give it will give it the name of the title by default -->
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Edit</h1>

  <%= render 'form' %>
</div>

app/views/messages/index.html.erb
<!-- the first part corresponds to the index action -->
<% @messages.each do |message| %>
  <div class="col-md-4">
    <div class="message">
      <h2 class="message-title"><%= message.title %></h2>
      <%= link_to "View Message", message_path(message), class: "btn-custom" %>
    </div>
  </div>
<% end %>
<!-- <p>#link_to "New Message", new_message_path </p> -->
<!--  link_to creates an anchor tag-->

app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>New message</h1>

  <%= render 'form' %>
</div>

app/views/messages/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="message-show">
    <h2><%= @message.title %></h2>
    <p class="message-posted-by">Posted by <%= @message.user.email %><%= time_ago_in_words(@message.created_at) %> ago</p>
    <!--  time stamp-->
    <p class="message-desc"><%= @message.description %></p>

    <h3>Comments:</h3>
    <!-- the @message has already found the message for show and .comments is simply pulling up the comments in relation to that message -->
    <%= render @message.comments %>

    <h3 class="reply-to-msg">Reply to Message:</h3>
    <%= render 'comments/form' %>
    <div class="links btn-group">
      <%= link_to "Back", root_path, class: "btn btn-default" %>
      <% if user_signed_in? %>
        <% if @message.user_id == current_user.id %>
          <%= link_to "Edit", edit_message_path(@message), class: "btn btn-default" %>
          <%= link_to "Delete", message_path(@message), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-default" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>